### ISSUE TITLE
[BUG] Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by Exozze** [davehornik/sd-discord-rich_presence#16]
[Discord Rich Presence]  Discord Rich Presence Extension, version 1.3.1
[Discord Rich Presence]  Bug reporting -> https://github.com/davehornik/sd-discord-rich_presence
*** Error executing callback ui_tabs_callback for E:\AI\stable-diffusion-webui\extensions\sd-discord-rich_presence\scripts\main.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "E:\AI\stable-diffusion-webui\extensions\sd-discord-rich_presence\scripts\main.py", line 138, in on_ui_tabs
        discord_broadcast()
      File "E:\AI\stable-diffusion-webui\extensions\sd-discord-rich_presence\scripts\main.py", line 25, in discord_broadcast
        broadcast.connect()
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\pypresence\presence.py", line 43, in connect
        self.loop.run_until_complete(self.handshake())
      File "C:\Users\Exozze\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
        return future.result()
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\pypresence\baseclient.py", line 116, in handshake
        self.sock_writer, _ = await asyncio.wait_for(self.loop.create_pipe_connection(lambda: reader_protocol, ipc_path), self.connection_timeout)
    AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'create_pipe_connection'

**Comment by davehornik** [comment]
https://github.com/davehornik/sd-discord-rich_presence/commit/b3767a195f1748c5453a96c0b7de295030fdcb41
